// <auto-generated by generate-cs-registry.js>
#nullable enable
using System.Collections.Frozen;

namespace Omnux.Middleware;

public sealed record CopilotModelMeta(string Provider, string PremiumMultiplier);

public static class ModelRegistry
{
    public static string GetDefaultModel(string provider)
        => Defaults.TryGetValue(provider, out var model) ? model : "unknown";

    public static string GetWorkerDefault(string provider)
        => WorkerDefaults.TryGetValue(provider, out var model) ? model : "none";

    public static IReadOnlyList<string> GetFallbackModels(string provider)
        => Fallbacks.TryGetValue(provider, out var list) ? list : Array.Empty<string>();

    public static string GetLabel(string provider)
        => Labels.TryGetValue(provider, out var label) ? label : provider;

    public static CopilotModelMeta? GetCopilotKnownMeta(string modelId)
        => CopilotKnownMeta.TryGetValue(modelId, out var meta) ? meta : null;
    private static readonly FrozenDictionary<string, string> Defaults = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = "meta-llama/llama-4-scout-17b-16e-instruct",
    ["gemini"] = "gemini-3.1-flash-lite",
    ["cerebras"] = "gpt-oss-120b",
    ["nvidia"] = "meta/llama-3.1-70b-instruct",
    ["copilot"] = "gpt-5-mini",
    ["codex"] = "gpt-5.5"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string> WorkerDefaults = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = "meta-llama/llama-4-scout-17b-16e-instruct",
    ["gemini"] = "gemini-3.1-flash-lite",
    ["cerebras"] = "gpt-oss-120b",
    ["nvidia"] = "meta/llama-3.1-70b-instruct",
    ["copilot"] = "none",
    ["codex"] = "none"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string> Labels = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = "Groq",
    ["gemini"] = "Gemini",
    ["cerebras"] = "Cerebras",
    ["nvidia"] = "NVIDIA NIM",
    ["copilot"] = "Copilot",
    ["codex"] = "Codex"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string[]> Fallbacks = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = new[] { "meta-llama/llama-4-scout-17b-16e-instruct", "openai/gpt-oss-120b", "openai/gpt-oss-20b", "llama-3.3-70b-versatile", "llama-3.1-8b-instant", "qwen/qwen3-32b", "groq/compound", "groq/compound-mini", "openai/gpt-oss-safeguard-20b" },
    ["gemini"] = new[] { "gemini-3.5-flash", "gemini-3.1-pro", "gemini-3-flash", "gemini-3.1-flash-lite" },
    ["cerebras"] = new[] { "gpt-oss-120b", "qwen-3-32b", "zai-glm-4.7" },
    ["nvidia"] = new[] { "meta/llama-3.1-70b-instruct", "meta/llama-3.3-70b-instruct", "nvidia/llama-3.3-nemotron-super-49b-v1.5", "openai/gpt-oss-120b" },
    ["copilot"] = new[] { "gpt-5.5", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.3-codex", "gpt-5-mini", "claude-sonnet-4.5", "claude-haiku-4.5", "gemini-3.1-pro", "gemini-3-flash" },
    ["codex"] = new[] { "gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.3-codex" }
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, CopilotModelMeta> CopilotKnownMeta = new Dictionary<string, CopilotModelMeta>(StringComparer.OrdinalIgnoreCase)
    {
    ["claude-sonnet-4.5"] = new("Anthropic", "1x"),
    ["claude-haiku-4.5"] = new("Anthropic", "0.33x"),
    ["gpt-5.5"] = new("OpenAI", "7.5x"),
    ["gpt-5.4-mini"] = new("OpenAI", "0.33x"),
    ["gpt-5.4-nano"] = new("OpenAI", "0.1x"),
    ["gpt-5.3-codex"] = new("OpenAI", "1x"),
    ["gpt-5-mini"] = new("OpenAI", "0x"),
    ["gemini-3.1-pro"] = new("Google", "1x"),
    ["gemini-3-flash"] = new("Google", "1x")
    }.ToFrozenDictionary();
}
