// <auto-generated by generate-cs-registry.js>
#nullable enable
using System.Collections.Frozen;

namespace Omnux.Middleware;

public sealed record CopilotModelMeta(string Provider, string PremiumMultiplier);

public static class ModelRegistry
{
    public static string GetDefaultModel(string provider)
        => Defaults.TryGetValue(provider, out var model) ? model : "unknown";

    public static string GetWorkerDefault(string provider)
        => WorkerDefaults.TryGetValue(provider, out var model) ? model : "none";

    public static IReadOnlyList<string> GetFallbackModels(string provider)
        => Fallbacks.TryGetValue(provider, out var list) ? list : Array.Empty<string>();

    public static string GetLabel(string provider)
        => Labels.TryGetValue(provider, out var label) ? label : provider;

    public static CopilotModelMeta? GetCopilotKnownMeta(string modelId)
        => CopilotKnownMeta.TryGetValue(modelId, out var meta) ? meta : null;
    private static readonly FrozenDictionary<string, string> Defaults = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = "qwen/qwen3.8-27b",
    ["gemini"] = "gemini-3.5-flash-lite",
    ["cerebras"] = "gpt-oss-120b",
    ["nvidia"] = "moonshotai/kimi-k3",
    ["copilot"] = "gpt-5-mini",
    ["codex"] = "gpt-6-astra",
    ["grok"] = "grok-4.6"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string> WorkerDefaults = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = "qwen/qwen3.8-27b",
    ["gemini"] = "gemini-3.5-flash-lite",
    ["cerebras"] = "gpt-oss-120b",
    ["nvidia"] = "moonshotai/kimi-k3",
    ["copilot"] = "none",
    ["codex"] = "none",
    ["grok"] = "none"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string> Labels = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = "Groq",
    ["gemini"] = "Gemini",
    ["cerebras"] = "Cerebras",
    ["nvidia"] = "NVIDIA NIM",
    ["copilot"] = "Copilot",
    ["codex"] = "Codex",
    ["grok"] = "Grok"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string[]> Fallbacks = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = new[] { "qwen/qwen3.8-27b", "openai/gpt-oss-120b", "openai/gpt-oss-20b", "qwen/qwen3.6-27b", "groq/compound", "groq/compound-mini" },
    ["gemini"] = new[] { "gemini-3.8-flash", "gemini-3.5-flash-lite", "gemini-3.7-flash", "gemini-3.6-flash", "gemini-3.1-pro-preview" },
    ["cerebras"] = new[] { "gpt-oss-120b", "qwen-3.8-27b" },
    ["nvidia"] = new[] { "moonshotai/kimi-k3", "deepseek-ai/deepseek-v4-pro-0813", "openai/gpt-oss-120b" },
    ["copilot"] = new[] { "gpt-6-astra", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.4-mini", "gpt-5-mini", "claude-sonnet-4.6", "claude-haiku-4.5", "gemini-3.8-flash" },
    ["codex"] = new[] { "gpt-6-astra", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.3-codex" },
    ["grok"] = new[] { "grok-4.6", "grok-4.5" }
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, CopilotModelMeta> CopilotKnownMeta = new Dictionary<string, CopilotModelMeta>(StringComparer.OrdinalIgnoreCase)
    {
    ["gpt-6-astra"] = new("OpenAI", "-"),
    ["gpt-5.6-sol"] = new("OpenAI", "-"),
    ["gpt-5.6-terra"] = new("OpenAI", "-"),
    ["gpt-5.6-luna"] = new("OpenAI", "-"),
    ["gpt-5.4-mini"] = new("OpenAI", "-"),
    ["gpt-5-mini"] = new("OpenAI", "-"),
    ["claude-sonnet-4.6"] = new("Anthropic", "-"),
    ["claude-haiku-4.5"] = new("Anthropic", "-"),
    ["gemini-3.8-flash"] = new("Google", "-")
    }.ToFrozenDictionary();
}
