// <auto-generated by generate-cs-registry.js>
#nullable enable
using System.Collections.Frozen;
using System.Text.RegularExpressions;

namespace Omnux.Middleware;

/// <summary>제공자가 서버측에서 직접 수행하는 웹 검색 방식. None 이면 외부 retriever 로 근거를 모아 넣는다.</summary>
public enum ProviderWebSearchMode
{
    None,
    GeminiGoogleSearch,
    GroqBrowserSearch,
    GroqCompound,
    DeepseekWebSearch,
    CliNative
}

/// <summary>추론 강도를 요청에 싣는 방식. 제공자마다 파라미터 이름과 허용값이 다르다.</summary>
public enum ProviderReasoningMode
{
    None,
    OpenAiEffort,
    GeminiThinkingLevel,
    NvidiaThinking,
    CliEffort
}

public sealed record ProviderCapabilityRule(
    string Match,
    ProviderWebSearchMode WebSearch,
    ProviderReasoningMode Reasoning,
    string[] Levels,
    string DefaultLevel
);

public sealed record ProviderCapability(
    string Provider,
    string Model,
    ProviderWebSearchMode WebSearch,
    ProviderReasoningMode Reasoning,
    IReadOnlyList<string> ReasoningLevels,
    string DefaultReasoningLevel
)
{
    public bool SupportsNativeWebSearch => WebSearch != ProviderWebSearchMode.None;

    public bool SupportsReasoningControl => Reasoning != ProviderReasoningMode.None && ReasoningLevels.Count > 0;

    /// <summary>요청받은 강도를 이 모델이 실제로 받는 값으로 좁힌다. 못 받으면 빈 문자열.</summary>
    public string NormalizeReasoningLevel(string? requested)
    {
        if (!SupportsReasoningControl)
        {
            return string.Empty;
        }

        var normalized = (requested ?? string.Empty).Trim().ToLowerInvariant();
        if (normalized.Length == 0 || normalized == "auto")
        {
            return DefaultReasoningLevel;
        }

        foreach (var level in ReasoningLevels)
        {
            if (string.Equals(level, normalized, StringComparison.OrdinalIgnoreCase))
            {
                return level;
            }
        }

        // 모델이 지원하지 않는 단계는 가장 가까운 단계로 내린다("minimal" 없는 모델의 minimal → low).
        var order = new[] { "off", "minimal", "low", "medium", "high" };
        var requestedIndex = Array.IndexOf(order, normalized);
        if (requestedIndex < 0)
        {
            return DefaultReasoningLevel;
        }

        var best = DefaultReasoningLevel;
        var bestDistance = int.MaxValue;
        foreach (var level in ReasoningLevels)
        {
            var index = Array.IndexOf(order, level.ToLowerInvariant());
            if (index < 0)
            {
                continue;
            }

            var distance = Math.Abs(index - requestedIndex);
            if (distance < bestDistance)
            {
                bestDistance = distance;
                best = level;
            }
        }

        return best;
    }
}

public static class ProviderCapabilityRegistry
{
    private static readonly FrozenDictionary<string, ProviderCapabilityRule[]> Rules = new Dictionary<string, ProviderCapabilityRule[]>(StringComparer.OrdinalIgnoreCase)
    {
    ["groq"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule("^openai/gpt-oss", ProviderWebSearchMode.GroqBrowserSearch, ProviderReasoningMode.OpenAiEffort, new[] { "low", "medium", "high" }, "medium"),
        new ProviderCapabilityRule("^groq/compound", ProviderWebSearchMode.GroqCompound, ProviderReasoningMode.None, Array.Empty<string>(), ""),
        new ProviderCapabilityRule(".", ProviderWebSearchMode.None, ProviderReasoningMode.None, Array.Empty<string>(), "")
    },
    ["gemini"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule("^gemini-3\\.6-flash", ProviderWebSearchMode.GeminiGoogleSearch, ProviderReasoningMode.GeminiThinkingLevel, new[] { "minimal", "low", "medium", "high" }, "low"),
        new ProviderCapabilityRule("^gemini-(3|2\\.5)", ProviderWebSearchMode.GeminiGoogleSearch, ProviderReasoningMode.GeminiThinkingLevel, new[] { "low", "medium", "high" }, "low"),
        new ProviderCapabilityRule(".", ProviderWebSearchMode.GeminiGoogleSearch, ProviderReasoningMode.None, Array.Empty<string>(), "")
    },
    ["cerebras"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule("^gpt-oss", ProviderWebSearchMode.None, ProviderReasoningMode.OpenAiEffort, new[] { "low", "medium", "high" }, "medium"),
        new ProviderCapabilityRule(".", ProviderWebSearchMode.None, ProviderReasoningMode.None, Array.Empty<string>(), "")
    },
    ["nvidia"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule("^(moonshotai/kimi|deepseek-ai/deepseek-v4|nvidia/nemotron)", ProviderWebSearchMode.None, ProviderReasoningMode.NvidiaThinking, new[] { "off", "on" }, "on"),
        new ProviderCapabilityRule(".", ProviderWebSearchMode.None, ProviderReasoningMode.None, Array.Empty<string>(), "")
    },
    ["deepseek"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule(".", ProviderWebSearchMode.DeepseekWebSearch, ProviderReasoningMode.OpenAiEffort, new[] { "low", "medium", "high" }, "medium")
    },
    ["copilot"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule(".", ProviderWebSearchMode.CliNative, ProviderReasoningMode.None, Array.Empty<string>(), "")
    },
    ["codex"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule(".", ProviderWebSearchMode.CliNative, ProviderReasoningMode.CliEffort, new[] { "low", "medium", "high" }, "medium")
    },
    ["grok"] = new ProviderCapabilityRule[]
    {
        new ProviderCapabilityRule(".", ProviderWebSearchMode.CliNative, ProviderReasoningMode.None, Array.Empty<string>(), "")
    }
    }.ToFrozenDictionary();

    private static readonly ProviderCapability Unknown = new(
        string.Empty,
        string.Empty,
        ProviderWebSearchMode.None,
        ProviderReasoningMode.None,
        Array.Empty<string>(),
        string.Empty
    );

    public static ProviderCapability Resolve(string? provider, string? model)
    {
        var providerKey = (provider ?? string.Empty).Trim();
        var modelId = (model ?? string.Empty).Trim();
        if (providerKey.Length == 0 || !Rules.TryGetValue(providerKey, out var rules))
        {
            return Unknown with { Provider = providerKey, Model = modelId };
        }

        if (modelId.Length == 0)
        {
            modelId = ModelRegistry.GetDefaultModel(providerKey);
        }

        foreach (var rule in rules)
        {
            if (!Regex.IsMatch(modelId, rule.Match, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant))
            {
                continue;
            }

            return new ProviderCapability(
                providerKey,
                modelId,
                rule.WebSearch,
                rule.Reasoning,
                rule.Levels,
                rule.DefaultLevel
            );
        }

        return Unknown with { Provider = providerKey, Model = modelId };
    }

    /// <summary>이 제공자에서 네이티브 웹 검색이 되는 모델 목록(fallback 카탈로그 기준).</summary>
    public static IReadOnlyList<string> ListNativeWebSearchModels(string provider)
    {
        return ModelRegistry.GetFallbackModels(provider)
            .Where(model => Resolve(provider, model).SupportsNativeWebSearch)
            .ToArray();
    }
}
